name: Publish
on:
  push:
    branches:
      - master
permissions:
  # tag
  contents: write
  # provenance
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: openbible-io/bump-and-publish@v0.3.3
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
