name: Publish
on:
  push:
    branches:
      - master
permissions:
  # tag
  contents: write
  # provenance
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bun test
      - uses: openbible-io/bump-and-publish@v0.2.0
